/** Templated questions are deterministic, bounded, and never generated by the LLM. */

import { describe, expect, it } from 'vitest';
import type { Candidate } from '@skem/shared';
import { buildQuestions } from '../../src/agent/questions.js';

const candidate = (code: string, label: string): Candidate => ({ code, label, confidence: 0.5 });

describe('buildQuestions', () => {
  it('asks participant scope with the four official scopes and unknown option', () => {
    const questions = buildQuestions(['participant_scope'], {
      category: [], level: [], role: [], achievement: [],
    });
    expect(questions[0]?.options.map((option) => option.value)).toEqual([
      'campus', 'regional', 'national', 'international', 'unknown',
    ]);
  });

  it('limits question count to three and uses candidate options', () => {
    const questions = buildQuestions(['category', 'role', 'achievement', 'activity_date'], {
      category: [candidate('K3-B01', 'Lomba'), candidate('K3-C01', 'Seni')],
      level: [],
      role: [candidate('Peserta', 'Peserta')],
      achievement: [candidate('Juara II', 'Juara II')],
    });
    expect(questions).toHaveLength(3);
    expect(questions[0]?.options.map((option) => option.value)).toEqual(['K3-B01', 'K3-C01']);
  });
});
